version: '3.8'

services:
  briefly-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: briefly-api
    restart: unless-stopped
    ports:
      - "5100:5100"
    volumes:
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - PORT=5100
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5100/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s